import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import * as core from "../src/codecks-core.ts";
import { useInertEnvironmentCredentialProvider } from "./credential-test-environment.ts";
useInertEnvironmentCredentialProvider();
const user="33333333-3333-4333-8333-333333333333"; const parse=(v:unknown)=>JSON.parse(String(v).match(/```json\s*([\s\S]*?)\s*```/)![1]);
let creates=0, searches=0; const original=globalThis.fetch; globalThis.fetch=(async(input)=>{if(String(input).includes('/dispatch/')) {creates++; if(creates===2)return new Response(JSON.stringify({message:'bad'}),{status:400}); return new Response(JSON.stringify({payload:{card:{id:`id-${creates}`,accountSeq:creates}}}),{status:200});} searches++; return new Response(JSON.stringify({data:{_root:{loggedInUser:user},user:{[user]:{id:user,name:'Sam'}}}}),{status:200});}) as typeof fetch;
try { const cards=[{title:'same',correlationKey:'csv-1'},{title:'same',correlationKey:'csv-2'},{title:'later'}]; const preview=parse(await core.card_bulk_create.execute({cards,dryRun:true,format:'json'})); const result=parse(await core.card_bulk_create.execute({cards,dryRun:false,expectedPreviewFingerprint:preview.data.previewFingerprint,format:'json'})); assert.equal(searches,2); assert.equal(creates,2); assert.equal(result.data.created,1); assert.equal(result.data.failed,1); assert.equal(result.data.definitelyUnsent,1); assert.equal(result.data.results[0].correlationKey,'csv-2'); assert.equal(result.data.results[1].status,'definitely_unsent'); const artifact=JSON.parse(readFileSync(result.data.artifact.path,'utf8')); assert.equal(artifact.results[0].correlationKey,'csv-1'); assert.equal(artifact.results[2].status,'definitely_unsent'); assert.equal('responseSchemaVersion' in result.data,false); assert.equal('duplicateDiscovery' in result.data,false); } finally {globalThis.fetch=original;}
console.log("bulk create simplification tests passed");
