import assert from 'node:assert/strict';
import { useInertEnvironmentCredentialProvider } from './credential-test-environment.ts';
import { fetchDoneTransitionEvents, type DoneTransitionObservation } from '../src/shared/done-transitions.ts';
import { runWithAbortSignal } from '../src/runtime/operation-context.ts';
useInertEnvironmentCredentialProvider();
const original = globalThis.fetch;
const requests: unknown[] = [];
let fail = false;
let failOffset: number | undefined;
let cardFields: Record<string, unknown> = { cardId: 'c', accountSeq: 0, title: null, status: false, derivedStatus: null, visibility: '', effort: 0, sprintId: null, assignee: null, deck: 'unresolved' };
let changer: unknown = 'unresolved';
globalThis.fetch = (async (_url, init) => {
  const query = JSON.parse(String(init?.body)).query;
  requests.push(query);
  if (fail) throw new Error('fixture scan failure');
  const relation = Object.keys(query._root[0].account[0])[0];
  if (failOffset !== undefined && JSON.parse(relation.slice('activities('.length, -1)).$offset >= failOffset) throw Error('fixture failed second page');
  const activity = { id: 'a', createdAt: '2026-04-28T01:00:00+00:00', type: 'card_update', data: { diff: { status: [null, ' DONE '] } }, card: 'c', changer };
  return new Response(JSON.stringify({ _root: { account: 'acct' }, account: { acct: { id: 'acct', [relation]: ['a'] } }, activity: { a: activity }, card: { c: cardFields } }), { headers: { 'Content-Type': 'application/json' } });
}) as typeof fetch;
try {
  const args = { sinceIso: '2026-04-28T00:00:00Z', until: new Date('2026-04-29'), scanLimit: 50, pageSize: 25 };
  const legacy = await fetchDoneTransitionEvents(args);
  const firstRequests = requests.splice(0);
  const observations: DoneTransitionObservation[] = [];
  const observed = await fetchDoneTransitionEvents({ ...args, observe: value => observations.push(value) });
  assert.deepEqual(observed, legacy);
  assert.deepEqual(requests.splice(0), firstRequests);
  assert.equal(observations.length, 1);
  assert.deepEqual(observations[0].card, { cardId: 'c', accountSeq: 0, title: null, status: false, derivedStatus: null, visibility: '', effort: 0, sprintId: null });
  assert.deepEqual(observations[0].transition, { from: null, to: ' DONE ' });
  assert.equal(observations[0].activity.createdAt, '2026-04-28T01:00:00+00:00');
  assert.equal(observations[0].event.doneAt, '2026-04-28T01:00:00.000Z');
  assert.equal(observations[0].event.title, '(untitled)');
  assert.equal(observations[0].relations.changer, 'unresolved');
  assert.equal(observations[0].relations.assignee, 'null');
  assert.equal(observations[0].relations.deck, 'unresolved');
  assert.equal(observations[0].assignee, null);
  assert.equal(observations[0].changer, undefined);
  const capped = await fetchDoneTransitionEvents({ ...args, pageSize: 1, scanLimit: 1 });
  assert.equal(capped.scanLimitReached, true);
  const controller = new AbortController(); controller.abort();
  const before = requests.length;
  await assert.rejects(() => runWithAbortSignal(controller.signal, () => fetchDoneTransitionEvents(args)));
  assert.equal(requests.length, before);
  cardFields = { cardId: 'c', accountSeq: null, status: 0, effort: null }; changer = { name: false, fullName: null };
  const missing: DoneTransitionObservation[] = [];
  await fetchDoneTransitionEvents({ ...args, observe: value => missing.push(value) });
  assert.equal(Object.hasOwn(missing[0].card!, 'title'), false);
  assert.equal(missing[0].card!.effort, null); assert.equal(missing[0].card!.accountSeq, null); assert.equal(missing[0].card!.status, 0);
  assert.equal(missing[0].changer!.name, false); assert.equal(missing[0].changer!.fullName, null);
  assert.equal(missing[0].relations.assignee, 'missing'); assert.equal(missing[0].relations.deck, 'missing');
  failOffset = 1; const partial: DoneTransitionObservation[] = []; const requestStart = requests.length;
  await assert.rejects(() => fetchDoneTransitionEvents({ ...args, pageSize: 1, scanLimit: 2, observe: value => partial.push(value) }));
  assert.equal(partial.length, 1); assert.equal(requests.length - requestStart, 2);
  failOffset = undefined; fail = true;
  await assert.rejects(() => fetchDoneTransitionEvents(args));
  console.log('cards done observation seam: legacy parity, native null/falsy, raw transition/date, relations, cap, abort and scan failure passed');
} finally { globalThis.fetch = original; }
