import { Type } from "typebox";
import { obj, str, ref, num, nullable, optional, list, envelope, projectReportsOutput } from "./reports-read-output";
export const REPORTS_FILE_LIMITS = { bytes: 262144, string: 2048, subjects: 100, periods: 500, transformations: 500, references: 500 } as const;
const choice = (...values: string[]) => Type.Union(values.map(v => Type.Literal(v)));
const kind = choice("observations", "csv", "markdown");
export const REPORTS_EFFECTS_SCHEMA = obj({ certainty: choice("not_written", "written", "indeterminate"), artifacts: list(obj({ kind, reference: Type.String({ minLength: 1, maxLength: 2048, "x-reference": true, pattern: String.raw`^(?![A-Za-z]:)(?![\\/])(?!.*(?:^|[\\/])\.\.(?:[\\/]|$)).+` }) }), 2), attempted: optional(kind), replayAllowed: Type.Literal(false) });
const coverage = list(obj({ from: str(), to: str(), status: choice("complete", "incomplete") }));
export const VELOCITY_UPDATE_OUTPUT_SCHEMA = envelope("velocity-observations-update", obj({ requestedMode: choice("incremental", "date_window", "full"), mode: Type.Literal("full"), window: obj({ from: str(), to: str() }), overlapDays: num(), complete: Type.Boolean(), visibility: Type.Literal("token_visible_projects_only_permissions_unverifiable"), runCount: num(), cardCount: num(), matchedCompletedRuns: num(), candidateRuns: num(), scannedActivities: num(), scanLimit: num(), scanLimitReached: Type.Boolean(), coverage: obj({ runs: coverage, deliveredCards: coverage }) }), REPORTS_EFFECTS_SCHEMA);
const config = obj({ id: nullable(ref()), name: nullable(str()), color: nullable(str()) });
const exclusion = obj({ fromDate: str(), toDate: str(), reason: str(), scope: choice("organization", "team", "person"), team: optional(str()), userId: optional(ref()), source: optional(str()) });
const args = obj({ measure: optional(str()), fromDate: optional(str()), toDate: optional(str()), selector: optional(nullable(str())), included: optional(list(config)), subject: optional(str()), userId: optional(nullable(ref())), team: optional(nullable(str())), membershipFrom: optional(nullable(str())), membershipTo: optional(nullable(str())), unassignedPolicy: optional(str()), decks: optional(list(obj({ id: nullable(ref()), title: nullable(str()), accountSeq: nullable(num()) }))), exclusions: optional(list(exclusion)), gapPolicy: optional(str()), partialPeriodPolicy: optional(str()), labels: optional(list(str())), allocation: optional(str()), anchor: optional(str()) });
const transformation = obj({ name: str(), contractVersion: Type.Literal(1), arguments: args, inputCount: num(), outputCount: num(), excludedReferences: list(obj({ reference: ref(), reason: str() })), excludedEffort: nullable(num()), warnings: list(str()) });
const period = obj({ startDate: str(), endDate: str(), label: str(), alignment: choice("monday_week", "fixed_biweekly"), anchor: str(), measure: choice("calendar_delivered", "run_attributed"), knownEffort: nullable(num()), presentationEffort: nullable(num()), deliveredCardCount: num(), missingEffortCount: num(), completeness: choice("complete", "partial_boundary", "gap", "missing_data"), valueKind: choice("observed", "modeled", "filled", "unavailable"), includedInStatistics: Type.Boolean(), contributingCards: list(ref()), contributingRuns: list(ref()), configurationIds: list(ref()) });
const summary = obj({ sampleWeeks: num(), totalEffort: num(), mean: nullable(num()), p25: nullable(num()), p50: nullable(num()), p75: nullable(num()), sampleStandardDeviation: nullable(num()), sampleVariance: nullable(num()), lowOutlierBound: nullable(num()), highOutlierBound: nullable(num()), statisticsAvailable: Type.Boolean(), varianceAvailable: Type.Boolean(), percentileMethod: Type.Literal("inclusive_linear_interpolation") });
const subject = obj({ name: str(), userId: nullable(ref()), team: nullable(str()), periods: list(period), biweekly: list(period), summary, composition: obj({ complete: num(), partial: num(), gapFilled: num(), excludedFromStatistics: num(), missingData: num() }) });
export const VELOCITY_REPORT_OUTPUT_SCHEMA = envelope("velocity-report", obj({ cacheSchemaVersion: Type.Literal(1), preset: str(), measure: choice("calendar_delivered", "run_attributed"), dateWindow: obj({ from: str(), to: str() }), configurationSelection: list(config), transformations: list(transformation), subjects: list(subject, 100), sourceSubjects: num(), sourceTransformations: num(), subjectPeriodCounts: list(obj({ periods: num(), biweekly: num() }), 100) }), REPORTS_EFFECTS_SCHEMA);
function safeEffects(native: any) {
 const artifacts = Array.isArray(native?.effects?.artifacts) ? native.effects.artifacts.filter((a: any) => ["observations", "csv", "markdown"].includes(a?.kind) && typeof a.reference === "string" && a.reference.length > 0 && Array.from(a.reference).length <= 2048 && !/^(?:[a-z]:|[\\/])|(?:^|[\\/])\.\.(?:[\\/]|$)/i.test(a.reference)).slice(0, 2) : [];
 const certainty = ["not_written", "written", "indeterminate"].includes(native?.effects?.certainty) ? native.effects.certainty : "indeterminate";
 return { certainty, artifacts, replayAllowed: false, ...(["observations", "csv", "markdown"].includes(native?.effects?.attempted) ? { attempted: native.effects.attempted } : {}) };
}
export const projectVelocityUpdateOutput = (native: unknown) => projectReportsOutput(VELOCITY_UPDATE_OUTPUT_SCHEMA, "velocity-observations-update", native, REPORTS_FILE_LIMITS.bytes, safeEffects(native));
export const projectVelocityReportOutput = (native: unknown) => projectReportsOutput(VELOCITY_REPORT_OUTPUT_SCHEMA, "velocity-report", native, REPORTS_FILE_LIMITS.bytes, safeEffects(native));
